backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-promotion
    tag: latest

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /promotion
