version: "3.8"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
  identity:
    image: quay.io/keycloak/keycloak:16.1.0
    command: ["-Djboss.http.port=80"]
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_USER: admin
      DB_PASSWORD: admin
      DB_ADDR: postgres
      DB_DATABASE: keycloak
  backoffice:
    image: ghcr.io/nashtech-garage/yas-backoffice-bff:latest
    entrypoint: ["./wait-for-it.sh", "identity:80", "--timeout=90", "--", "java", "-jar", "/backoffice-bff-0.0.1-SNAPSHOT.jar"]
    environment:
      SERVER_PORT: "80"
      SPRING_PROFILES_ACTIVE: prod
      #SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://identity:8080/auth/realms/Yas
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: api
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://nginx
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /api/**
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: RewritePath=/api/(?<segment>.*), /$$\{segment}
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[1]: TokenRelay=
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: nextjs
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://backoffice-nextjs:3000
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /**
  backoffice-nextjs:
    image: ghcr.io/nashtech-garage/yas-backoffice:latest
  media:
    image: ghcr.io/nashtech-garage/yas-media:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/media
      SERVER_SERVLET_CONTEXT_PATH: /media
      YAS_PUBLICURL: http://api.yas.local/media
      SERVER_PORT: "80"
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  product:
    image: ghcr.io/nashtech-garage/yas-product:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product
      SERVER_SERVLET_CONTEXT_PATH: /product
      YAS_SERVICES_MEDIA: http://media/media
      SERVER_PORT: "80"
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      BASE_URL: /swagger-ui
      URLS: "[{ url: 'http://api.yas.local/product/v3/api-docs', name: 'Product' },{ url: 'http://api.yas.local/media/v3/api-docs', name: 'Media' }]"
      OAUTH_CLIENT_ID: swagger-ui
      OAUTH_USE_PKCE: "true"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yas.com
      PGADMIN_DEFAULT_PASSWORD: admin
  jaeger:
    image: jaegertracing/all-in-one:1.36
    ports:
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
volumes:
  postgres:
  pgadmin:
