{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "backend.fullname" . }}-serviceMonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backend.fullname" . }}
  endpoints:
    - port: 'metric'
      path: '/actuator/prometheus'
  {{- end }}