backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-tax
    tag: latest

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /tax
