name: backoffice-bff service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "backoffice-bff/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/backoffice-bff-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backoffice-bff/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/backoffice-bff-ci.yaml"
      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -f backoffice-bff
      - name: Analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f backoffice-bff
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./backoffice-bff
          push: true
          tags: ghcr.io/nashtech-garage/yas-backoffice-bff:latest
